<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="3" passed="2" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2025-01-04T21:09:31 IST" name="Suite" finished-at="2025-01-04T21:10:10 IST" duration-ms="39881">
    <groups>
      <group name="ErrorHandlings">
        <method signature="ErrorValidations.LoginErrorVal()[pri:0, instance:Prashanth_maven_project.Tests.ErrorValidations@35b74c5c]" name="LoginErrorVal" class="Prashanth_maven_project.Tests.ErrorValidations"/>
      </group> <!-- ErrorHandlings -->
      <group name="purchase">
        <method signature="SubmitOrderTest.StandAlone(java.util.HashMap)[pri:0, instance:Prashanth_maven_project.Tests.SubmitOrderTest@5a7fe64f]" name="StandAlone" class="Prashanth_maven_project.Tests.SubmitOrderTest"/>
      </group> <!-- purchase -->
    </groups>
    <test started-at="2025-01-04T21:09:31 IST" name="SubmitOrderTest" finished-at="2025-01-04T21:10:01 IST" duration-ms="30907">
      <class name="Prashanth_maven_project.Tests.SubmitOrderTest">
        <test-method is-config="true" signature="launchapp()[pri:0, instance:Prashanth_maven_project.Tests.SubmitOrderTest@5a7fe64f]" started-at="2025-01-04T21:09:31 IST" name="launchapp" finished-at="2025-01-04T21:09:40 IST" duration-ms="9422" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchapp -->
        <test-method signature="StandAlone(java.util.HashMap)[pri:0, instance:Prashanth_maven_project.Tests.SubmitOrderTest@5a7fe64f]" started-at="2025-01-04T21:09:40 IST" name="StandAlone" data-provider="getData" finished-at="2025-01-04T21:09:50 IST" duration-ms="10025" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[{pwd=Sparkz1234, email=sparkz1@gmail.com, prod=ADIDAS ORIGINAL}]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- StandAlone -->
        <test-method is-config="true" signature="close()[pri:0, instance:Prashanth_maven_project.Tests.SubmitOrderTest@5a7fe64f]" started-at="2025-01-04T21:09:50 IST" name="close" finished-at="2025-01-04T21:09:51 IST" duration-ms="598" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- close -->
        <test-method is-config="true" signature="launchapp()[pri:0, instance:Prashanth_maven_project.Tests.SubmitOrderTest@5a7fe64f]" started-at="2025-01-04T21:09:51 IST" name="launchapp" finished-at="2025-01-04T21:09:59 IST" duration-ms="8582" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchapp -->
        <test-method signature="VerifyOrders()[pri:0, instance:Prashanth_maven_project.Tests.SubmitOrderTest@5a7fe64f]" started-at="2025-01-04T21:09:59 IST" name="VerifyOrders" finished-at="2025-01-04T21:10:01 IST" depends-on-methods="Prashanth_maven_project.Tests.SubmitOrderTest.StandAlone" duration-ms="1747" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- VerifyOrders -->
        <test-method is-config="true" signature="close()[pri:0, instance:Prashanth_maven_project.Tests.SubmitOrderTest@5a7fe64f]" started-at="2025-01-04T21:10:01 IST" name="close" finished-at="2025-01-04T21:10:01 IST" duration-ms="375" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- close -->
      </class> <!-- Prashanth_maven_project.Tests.SubmitOrderTest -->
    </test> <!-- SubmitOrderTest -->
    <test started-at="2025-01-04T21:10:03 IST" name="Error Validations" finished-at="2025-01-04T21:10:10 IST" duration-ms="7935">
      <class name="Prashanth_maven_project.Tests.ErrorValidations">
        <test-method is-config="true" signature="launchapp()[pri:0, instance:Prashanth_maven_project.Tests.ErrorValidations@35b74c5c]" started-at="2025-01-04T21:10:03 IST" name="launchapp" finished-at="2025-01-04T21:10:08 IST" duration-ms="5597" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchapp -->
        <test-method signature="LoginErrorVal()[pri:0, instance:Prashanth_maven_project.Tests.ErrorValidations@35b74c5c]" started-at="2025-01-04T21:10:08 IST" name="LoginErrorVal" finished-at="2025-01-04T21:10:10 IST" duration-ms="1798" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Incorrect email or password.] but found [Incorrect emaill or password.]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Incorrect email or password.] but found [Incorrect emaill or password.]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at org.testng.Assert.assertEquals(Assert.java:666)
at Prashanth_maven_project.Tests.ErrorValidations.LoginErrorVal(ErrorValidations.java:33)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:228)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:961)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:201)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:819)
at org.testng.TestRunner.run(TestRunner.java:619)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1228)
at org.testng.TestNG.runSuites(TestNG.java:1134)
at org.testng.TestNG.run(TestNG.java:1101)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- LoginErrorVal -->
        <test-method is-config="true" signature="close()[pri:0, instance:Prashanth_maven_project.Tests.ErrorValidations@35b74c5c]" started-at="2025-01-04T21:10:10 IST" name="close" finished-at="2025-01-04T21:10:10 IST" duration-ms="224" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- close -->
      </class> <!-- Prashanth_maven_project.Tests.ErrorValidations -->
    </test> <!-- Error Validations -->
  </suite> <!-- Suite -->
</testng-results>
